---
- hosts: cisco_sg
  gather_facts: false
  connection: local
  vars:
    firmware_filename: c2960x-universalk9-mz.152-7.E2.bin
    tftp_ip: 192.168.51.130
    cli:
      host: "10.12.0.203"
      username: admin
      password: P@ssw0rd
      timeout: 420
  tasks:
      - name: IOS become user
        no_log: True
        ios_command:
          commands:
            - command: enable
              prompt: "Password:"
              answer: "{{ cli.password }}"  
          provider: "{{ cli }}"
 
      - name: IOS Copy from TFTP
        ios_command:
          commands:
          - command: "copy tftp: {{ firmware_filename }}"
            check_all: True
            prompt:
              - "Address or name of remote host"
              - "Source filename"
              - "Destination filename"
            answer: 
              - "{{ tftp_ip }}"
              - "{{ firmware_filename }}"
              - "test-{{ firmware_filename }}"
          provider: "{{ cli }}"
