---
- hosts:  all
  serial: 1
  ignore_errors: no
  gather_facts: no
  connection: network_cli
  tasks:
    - name: GATHER SWITCH FACTS
      ios_facts:

    - name: UPGRADE IOS IMAGE IF NOT COMPLIANT
      block:
      - name: COPY OVER IOS IMAGE
        ios_command:
           commands:
              - command: "copy flash:/c2960x-universalk9-mz.152-2.E7/c2960x-universalk9-mz.152-2.E7.bin tftp: host: 192.168.51.130"
              - host: 192.168.51.130
              
        vars:
          ansible_command_timeout: 1800  
 



