---
- hosts:  all
  serial: 1
  ignore_errors: no
  gather_facts: no
  connection: network_cli
  tasks:
    - name: GATHER ROUTER FACTS
      ios_facts:

    - name: UPGRADE IOS IMAGE IF NOT COMPLIANT
      block:
      - name: COPY OVER IOS IMAGE
        command: "scp c2960x-universalk9-mz.152-2.E7.bin 192.168.51.130/test.bin"  




