---
- name: Cisco Command
  hosts: all
  serial: 1
  ignore_errors: no
  gather_facts: no
  connection: local
  vars:
    logText: ""
  tasks:
    - name: Ansible delete file
      file:
        path: "/tmp/cisco/{{ inventory_hostname }}.csv"
        state: absent
        owner: awx
        group: awx
        mode: "0644"

    - name: Ansible create file
      file:
        path: "/tmp/cisco/{{ inventory_hostname }}.csv"
        state: touch

    - name: append
      lineinfile:
        path: /tmp/cisco/{{ inventory_hostname }}.csv
        line: "Results from cisco device - {{ inventory_hostname }}"

    - name: append dash-line
      lineinfile:
        path: /tmp/cisco/{{ inventory_hostname }}.csv
        line: "-----------------------------------"

    - name: deploy files with network address in them
      include_tasks: cisco-apex7-block-task.yml
      loop:
        - { name: 'Cisco Command 4.1',task_id: 'SN4.1', command: sh running-config | beg banner exec }
        - { name: 'Cisco Command 4.2',task_id: 'SN4.2', command: running-config | beg banner login }
        - { name: 'Cisco Command 4.3',task_id: 'SN4.3', command: sh running-config | beg banner motd }
        - { name: 'Cisco Command 6.3',task_id: 'SN6.3', command: show run | incl snmp-server community }
    - name: Write Log to File
      lineinfile:
        path: /tmp/cisco/{{ inventory_hostname }}.csv
        line: "{{logText | trim}}"
