---
- name: Cisco Command
  hosts: all
  serial: 1
  ignore_errors: no
  gather_facts: no
  connection: local
  vars:
    logText: ""
  tasks:
    - name: Ansible delete file
      file:
        path: "/tmp/cisco/{{ inventory_hostname }}.csv"
        state: absent
        owner: awx
        group: awx
        mode: "0644"

    - name: Ansible create file
      file:
        path: "/tmp/cisco/{{ inventory_hostname }}.csv"
        state: touch

    - name: append
      lineinfile:
        path: /tmp/cisco/{{ inventory_hostname }}.csv
        line: "Results from cisco device - {{ inventory_hostname }}"

    - name: append dash-line
      lineinfile:
        path: /tmp/cisco/{{ inventory_hostname }}.csv
        line: "-----------------------------------"

    - name: deploy files with network address in them
      include_tasks: cisco-apex7-block-task.yml
      loop:
        - { name: 'Cisco Command 2.1',task_id: 'SN2.1', command: show running-config | incl aaa new-model }
        - { name: 'Cisco Command 2.2',task_id: 'SN2.2', command: show run | incl aaa authentication login }
        - { name: 'Cisco Command 2.3',task_id: 'SN2.3', command: sshow running-config | incl aaa authentication enable }
        - { name: 'Cisco Command 2.4',task_id: 'SN2.4', command: sh run | sec line | incl login authentication }
        - { name: 'Cisco Command 2.5',task_id: 'SN2.5', command: sh run | sec line | incl login authentication }
        - { name: 'Cisco Command 2.6',task_id: 'SN2.6', command: sh run | incl aaa accounting commands }
        - { name: 'Cisco Command 2.7',task_id: 'SN2.7', command: sh run | incl aaa accounting connection }
        - { name: 'Cisco Command 2.8',task_id: 'SN2.8', command: sh run | incl aaa accounting exec }
        - { name: 'Cisco Command 2.9',task_id: 'SN2.9', command: sh run | incl aaa accounting network }
        - { name: 'Cisco Command 3.1',task_id: 'SN3.1', command: show run | incl privilege }
        - { name: 'Cisco Command 3.2',task_id: 'SN3.2', command: show run | incl privilege }
        - { name: 'Cisco Command 3.3',task_id: 'SN3.3', command: show run | incl privilege }
        - { name: 'Cisco Command 3.4',task_id: 'SN3.4', command: sh run | sec vty }
        - { name: 'Cisco Command 3.5',task_id: 'SN3.5', command: sh run | sec aux }
        - { name: 'Cisco Command 3.6',task_id: 'SN3.6', command: sh run | sec aux }
        - { name: 'Cisco Command 3.7',task_id: 'SN3.7', command: sh run | sec aux }
        - { name: 'Cisco Command 3.8',task_id: 'SN3.8', command: sh run | sec line aux 0 }
        - { name: 'Cisco Command 3.9',task_id: 'SN3.9', command: sh run | sec line aux 0 }
        - { name: 'Cisco Command 4.1',task_id: 'SN4.1', command: sh running-config | beg banner exec }
        - { name: 'Cisco Command 4.2',task_id: 'SN4.2', command: running-config | beg banner login }
        - { name: 'Cisco Command 4.3',task_id: 'SN4.3', command: sh running-config | beg banner motd }
        - { name: 'Cisco Command 5.1',task_id: 'SN5.1', command: sh run | incl enable secret }
        - { name: 'Cisco Command 5.2',task_id: 'SN5.2', command: sh run | incl enable secret }
        - { name: 'Cisco Command 6.1',task_id: 'SN6.1', command: show snmp community }
        - { name: 'Cisco Command 6.2',task_id: 'SN6.2', command: show snmp community }
        - { name: 'Cisco Command 6.3',task_id: 'SN6.3', command: show run | incl snmp-server community }
        - { name: 'Cisco Command 6.4',task_id: 'SN6.4', command: show run snmp-server }
        - { name: 'Cisco Command 6.5',task_id: 'SN6.5', command: show run snmp-server }
        - { name: 'Cisco Command 6.6',task_id: 'SN6.6', command: show snmp groups }
        - { name: 'Cisco Command 6.7',task_id: 'SN6.7', command: show snmp user }
        - { name: 'Cisco Command 7.1',task_id: 'SN7.1', command: show ssh }
        - { name: 'Cisco Command 7.2',task_id: 'SN7.2', command: show ssh }
        - { name: 'Cisco Command 8.1',task_id: 'SN8.1', command: sh run | incl hostname }
        - { name: 'Cisco Command 8.2',task_id: 'SN8.2', command: sh run | incl domain name }
        - { name: 'Cisco Command 8.3',task_id: 'SN8.3', command: sh crypto key mypubkey rsa }
        - { name: 'Cisco Command 8.4',task_id: 'SN8.4', command: sh ip ssh }
        - { name: 'Cisco Command 8.5',task_id: 'SN8.5', command: sh ip ssh }
        - { name: 'Cisco Command 8.6',task_id: 'SN8.6', command: sh ip ssh }
        - { name: 'Cisco Command 8.7',task_id: 'SN8.7', command: show cdp }
        - { name: 'Cisco Command 8.8',task_id: 'SN8.8', command: show run | incl bootp }
        - { name: 'Cisco Command 8.9',task_id: 'SN8.9', command: show run | incl dhcp }
        - { name: 'Cisco Command 8.10',task_id: 'SN8.10', command: show run | incl identd }
        - { name: 'Cisco Command 8.11',task_id: 'SN8.11', command: show run | incl service tcp }
        - { name: 'Cisco Command 8.12',task_id: 'SN8.12', command: show run | incl service tcp }
        - { name: 'Cisco Command 8.13',task_id: 'SN8.13', command: show run | incl service pad }
        - { name: 'Cisco Command 9.1',task_id: 'SN9.1', command: show run | incl logging on }
        - { name: 'Cisco Command 9.2',task_id: 'SN9.2', command: show run | incl logging buffered }
        - { name: 'Cisco Command 9.3',task_id: 'SN9.3', command: show run | incl logging console }
        - { name: 'Cisco Command 9.4',task_id: 'SN9.4', command: sh log | incl logging host }
        - { name: 'Cisco Command 9.5',task_id: 'SN9.5', command: sh log | incl trap logging }
        - { name: 'Cisco Command 9.6',task_id: 'SN9.6', command: sh run | incl service timestamps }
        - { name: 'Cisco Command 9.7',task_id: 'SN9.7', command: sh run | incl logging source }
        - { name: 'Cisco Command 10.1',task_id: 'SN10.1', command: sh ntp associations }
        - { name: 'Cisco Command 10.2',task_id: 'SN10.2', command: sh ip int brief | incl Loopback }
        - { name: 'Cisco Command 10.3',task_id: 'SN10.3', command: sh run | incl ntp source }
        - { name: 'Cisco Command 11.11',task_id: 'SN11.11', command: sh run | sec router ospf }
        - { name: 'Cisco Command 11.12',task_id: 'SN11.12', command: "sh run int {interface}" }
        - { name: 'Cisco Command 11.21',task_id: 'SN11.21', command: sh run | sec router bgp }
    - name: Write Log to File
      lineinfile:
        path: /tmp/cisco/{{ inventory_hostname }}.csv
        line: "{{logText | trim}}"
