---
- hosts:  all
  ansible_become: yes
  ansible_become_method: enable
  tasks:
      - name: run multiple commands on remote nodes
        ios_command:
          commands:
            - copy flash:C2960X-UNIVERSALK9-M tftp:
