---
- hosts:  all
  serial: 1
  ignore_errors: no
  gather_facts: no
  connection: network_cli
  tasks:
    - name: block
      block:
      - name: run multiple commands on remote nodes
        ios_command:
          commands:
            - copy flash:/c2960x-universalk9-mz.152-2.E7/c2960x-universalk9-mz.152-2.E7.bin tftp:
              host: "{{tftp}}"
              answer: "\r"


