---
- hosts:  all
  tasks:
    - name: block
      block:
      - name: run multiple commands on remote nodes
        ios_command:
          commands:
            - copy flash:/c2960x-universalk9-mz.152-2.E7/c2960x-universalk9-mz.152-2.E7.bin tftp:
              prompt: '[{{ host }}]'
              answer: "\r"


