---
- hosts:  all
  serial: 1
  ignore_errors: yes
  gather_facts: no
  connection: local
  tasks:
    - name: GATHER SWITCH FACTS
      ios_facts:

    - name: UPGRADE IOS IMAGE IF NOT COMPLIANT
      block:
      - name: COPY OVER IOS IMAGE
        ios_command:
           commands:
              - copy flash:/c2960x-universalk9-mz.152-2.E7/c2960x-universalk9-mz.152-2.E7.bin tftp:'192.168.51.130'
        vars:
          ansible_command_timeout: 1800  
 



