---
- hosts:  all
  tasks:
      - name: run multiple commands on remote nodes
        ios_command:
          commands:
            - copy flash:/c2960x-universalk9-mz.152-2.E7/c2960x-universalk9-mz.152-2.E7.bin tftp:
              check_all: True
              prompt:
                - 'Address or name of remote host'
              answer:
                - '<ip address ftp server>'
              vars:
                ansible_command_timeout: 1200

